###
POST http://localhost:3000/api/create
content-type: application/json

 {
  "name": "Dor",
  "email": "dor@gmail.com",
  "phoneNumber": "05369567423"
 }
###

GET http://localhost:3000/api/

###

DELETE  http://localhost:3000/api/delete/61bf3c1dc07d3fcecd644dc3

###
PUT http://localhost:3000/api/update/61bf3cc8c07d3fcecd644dc9
content-type: application/json

{
  "name": "Jony",
  "email": "Camony@gmail.com",
  "phoneNumber": "05369567423"
 }
###